// examples/minimal-nuxt/app.vue
<template>
  <div>Nuxt x UploadThing</div>
  <UploadButton
    :config="{
      endpoint: 'videoAndImage',
      onClientUploadComplete(res) {
        console.log(`onClientUploadComplete`, res);
        alert('Upload Completed');

        res[0]?.serverData;
      },
      onUploadBegin: () => {
        console.log(`onUploadBegin`);
      },
    }"
  />

  <UploadDropzone
    :config="{
      endpoint: 'e2',
      onClientUploadComplete(res) {
        console.log(`onClientUploadComplete`, res);
        alert('Upload Completed');

        res[0]?.serverData;
      },
      onUploadBegin: () => {
        console.log(`onUploadBegin`);
      },
    }"
  />

  <input
    type="file"
    @change="
      async (e) => {
        console.log(`e`, e);
        const file = (e.target as HTMLInputElement).files?.[0];
        if (!file) return;

        // Do something with files

        // Then start the upload
        await startUpload([file]);
      }
    "
  />
</template>

<script setup lang="ts">
const alert = (msg: string) => {
  window.alert(msg);
};

const { startUpload } = useUploadThing("videoAndImage", {
  onClientUploadComplete(res) {
    console.log(`onClientUploadComplete`, res);
    alert("Upload Completed");
  },
});
</script>

// examples/with-tailwindcss/src/app/page.tsx
"use client";

import {
  UploadButton,
  UploadDropzone,
  useUploadThing,
} from "~/utils/uploadthing";

export default function Home() {
  const { startUpload } = useUploadThing("videoAndImage", {
    onClientUploadComplete: () => {
      alert("Upload Completed");
    },
  });

  return (
    <main className="mx-auto flex min-h-screen max-w-sm flex-col items-center justify-center gap-4 py-24">
      <UploadButton
        endpoint="videoAndImage"
        onClientUploadComplete={(res) => {
          console.log(`onClientUploadComplete`, res);
          alert("Upload Completed");
        }}
        onUploadBegin={() => {
          console.log("upload begin");
        }}
        config={{
          appendOnPaste: true,
        }}
      />
      <UploadDropzone
        className="ut-label:text-lg ut-allowed-content:ut-uploading:text-red-300 ut-allowed-content:text-white w-full bg-slate-800"
        endpoint="videoAndImage"
        onClientUploadComplete={(res) => {
          console.log(`onClientUploadComplete`, res);
          alert("Upload Completed");
        }}
        onUploadBegin={() => {
          console.log("upload begin");
        }}
      />
      <input
        type="file"
        className="border-input placeholder:text-muted-foreground focus-visible:ring-ring flex h-9 w-full rounded-md border bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium focus-visible:outline-none focus-visible:ring-1 disabled:cursor-not-allowed disabled:opacity-50"
        onChange={async (e) => {
          const file = e.target.files?.[0];
          if (!file) return;

          // Do something with files

          // Then start the upload
          await startUpload([file]);
        }}
      />
    </main>
  );
}
