// packages/vue/src/components.tsx
import { defineComponent } from "vue";

import type { FileRouter } from "uploadthing/server";

import type { UploadthingComponentProps } from "./types";
import { UploadButton } from './components/button'
import { UploadDropzone } from "./components/dropzone";
import { Spinner } from "./components/shared";

export {
  UploadButton,
  UploadDropzone,
  Spinner
}

export const Uploader = <
  TRouter extends FileRouter,
  TEndpoint extends keyof TRouter,
>() =>
  defineComponent(
    (_props: { config: UploadthingComponentProps<TRouter, TEndpoint> }) => {
      return () => {
        return (
          <>
            <div class="ut-flex ut-flex-col ut-items-center ut-justify-center ut-gap-4">
              <span class="ut-text-center ut-text-4xl ut-font-bold">
                {`Upload a file using a button:`}
              </span>
              {/* @ts-expect-error - this is validated above */}
              <UploadButton<TRouter> {...props} />
            </div>
            <div class="ut-flex ut-flex-col ut-items-center ut-justify-center ut-gap-4">
              <span class="ut-text-center ut-text-4xl ut-font-bold">
                {`...or using a dropzone:`}
              </span>
              {/* @ts-expect-error - this is validated above */}
              <UploadDropzone<TRouter> {...props} />
            </div>
          </>
        );
      };
    },
    {
      props: ["config"],
    },
  );

// builder function to create generic component inside of SFC setup script
export const useUploadButton = <TRouter extends FileRouter>() => {
  // @ts-expect-error - FIXME: need TEndpoint somehow
  return UploadButton<TRouter>();
};

export const useUploadDropzone = <TRouter extends FileRouter>() => {
  // @ts-expect-error - FIXME: need TEndpoint somehow
  return UploadDropzone<TRouter>();
};

export const useUploader = <TRouter extends FileRouter>() => {
  // @ts-expect-error - FIXME: need TEndpoint somehow
  return Uploader<TRouter>();
};

// examples/minimal-astro-react/src/components/page.tsx
import { UploadButton } from "@uploadthing/react";

import type { OurFileRouter } from "../server/uploadthing";

export default function Page() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center  gap-16 p-24">
      <div className="flex flex-col items-center justify-center gap-4">
        <span className="text-center text-4xl font-bold">
          {`Upload a file using a button:`}
        </span>

        <UploadButton<OurFileRouter>
          endpoint="videoAndImage"
          onClientUploadComplete={(res) => {
            // Do something with the response
            console.log("Files: ", res);
            alert("Upload Completed");
          }}
          onUploadError={(error: Error) => {
            console.log(error.stack);
            alert(`ERROR! ${error.message}`);
          }}
        />
      </div>
    </main>
  );
}
