// packages/react/src/components/uploader.tsx
import type { FileRouter } from "uploadthing/server";

import type { EndpointHelper } from "./component-helpers";
import { UploadButton } from "./upload-button";
import { UploadDropzone } from "./upload-dropzone";

export const Uploader = <TRouter extends void | FileRouter = void>(props: {
  endpoint: EndpointHelper<TRouter>;
  onClientUploadComplete?: () => void;
  url?: string;
}) => {
  return (
    <>
      <div className="flex flex-col items-center justify-center gap-4">
        <span className="text-center text-4xl font-bold">
          {`Upload a file using a button:`}
        </span>
        <UploadButton<TRouter> {...props} />
      </div>
      <div className="flex flex-col items-center justify-center gap-4">
        <span className="text-center text-4xl font-bold">
          {`...or using a dropzone:`}
        </span>
        <UploadDropzone<TRouter> {...props} />
      </div>
    </>
  );
};

// packages/svelte/src/lib/component/Uploader.svelte
<script lang="ts" generics="TRouter extends FileRouter">
  import type { FileRouter } from "uploadthing/server";

  import type { UploadthingComponentProps } from "./shared";
  import UploadButton from "./UploadButton.svelte";
  import UploadDropzone from "./UploadDropzone.svelte";

  export let uploader: UploadthingComponentProps<TRouter>;
</script>

<div class="ut-flex ut-flex-col ut-items-center ut-justify-center ut-gap-4">
  <span class="ut-text-center ut-text-4xl ut-font-bold">
    {`Upload a file using a button:`}
  </span>
  <UploadButton {uploader} />
</div>
<div class="ut-flex ut-flex-col ut-items-center ut-justify-center ut-gap-4">
  <span class="ut-text-center ut-text-4xl ut-font-bold">
    {`...or using a dropzone:`}
  </span>
  <UploadDropzone {uploader} />
</div>
