// examples/appdir/src/app/page.tsx
"use client";

import { Inter } from "next/font/google";
import { UploadButton, UploadDropzone } from "@uploadthing/react";
import type { OurFileRouter } from "./_uploadthing";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center  gap-16 p-24">
      <div className="flex flex-col items-center justify-center gap-4">
        <span className="text-4xl font-bold text-center">
          {`Upload a file using a button:`}
        </span>
        <UploadButton<OurFileRouter>
          endpoint="withoutMdwr"
          onClientUploadComplete={() => {
            alert("Upload Completed");
          }}
        />
      </div>
      <div className="flex flex-col items-center justify-center gap-4">
        <span className="text-4xl font-bold text-center">
          {`...or using a dropzone:`}
        </span>
        <UploadDropzone<OurFileRouter>
          endpoint="withoutMdwr"
          onClientUploadComplete={() => {
            alert("Upload Completed");
          }}
        />
      </div>
    </main>
  );
}

// examples/backend-adapters/client-vue/src/App.vue
<script setup lang="ts">
import { UploadButton, UploadDropzone } from "./uploadthing";

function alert(message: string) {
  window.alert(message);
}
</script>

<template>
  <main className="flex flex-col items-center gap-4 py-8">
    <h1 className="text-xl font-bold">Hello from H3!</h1>
    <div>
      <UploadButton
        :config="{
          config: {
            mode: 'manual',
            appendOnPaste: true,
          },
          endpoint: 'videoAndImage',
          onClientUploadComplete: (file) => {
            console.log('uploaded', file);
            alert('Upload complete');
          },
          onUploadError: (error) => {
            console.error(error, error.cause);
            alert('Upload failed');
          },
        }"
      />
      <UploadDropzone
        :config="{
          config: {
            mode: 'manual',
            appendOnPaste: true,
          },
          endpoint: 'videoAndImage',
          onClientUploadComplete: (file) => {
            console.log('uploaded', file);
            alert('Upload complete');
          },
          onUploadError: (error) => {
            console.error(error, error.cause);
            alert('Upload failed');
          },
        }"
      />
    </div>
  </main>
</template>
