// examples/minimal-sveltekit/src/routes/+page.svelte
<script lang="ts">
  import { createUploader, useUploadThing } from "$lib/utils/uploadthing";

  import { UploadButton, UploadDropzone } from "@uploadthing/svelte";

  import "@fontsource-variable/inter";

  const uploader = createUploader("videoAndImage", {
    onClientUploadComplete: (res) => {
      console.log(`onClientUploadComplete`, res);
      alert("Upload Completed");
    },
    onUploadError: (error: Error) => {
      alert(`ERROR! ${error.message}`);
    },
  });

  const { startUpload } = useUploadThing("videoAndImage", {
    /**
     * @see https://docs.uploadthing.com/api-reference/react#useuploadthing
     */
    onClientUploadComplete: (res) => {
      console.log(`onClientUploadComplete`, res);
      alert("Upload Completed");
    },
  });
</script>

<main>
  <UploadButton
    {uploader}
  />
  <UploadDropzone
    {uploader}
  />
  <input
    type="file"
    on:change={async (e) => {
      const file = e.currentTarget.files?.[0];
      if (!file) return;

      // Do something with files

      // Then start the upload
      await startUpload([file]);
    }}
  />
</main>

<style>
  :global(body) {
    font-family: "Inter Variable", sans-serif;
  }
</style>

// examples/minimal-solidstart/src/routes/index.tsx
import {
  UploadButton,
  UploadDropzone,
  useUploadThing,
} from "~/utils/uploadthing";

export default function Home() {
  const { startUpload } = useUploadThing("videoAndImage", {
    onClientUploadComplete: () => {
      alert("Upload Completed");
    },
  });

  return (
    <main>
      <UploadButton
        endpoint="videoAndImage"
        multiple
        onClientUploadComplete={(res) => {
          console.log(`onClientUploadComplete`, res);
          alert("Upload Completed");
        }}
        onUploadBegin={() => {
          console.log("upload begin");
        }}
      />
      <UploadDropzone
        endpoint="videoAndImage"
        multiple
        onClientUploadComplete={(res) => {
          console.log(`onClientUploadComplete`, res);
          alert("Upload Completed");
        }}
        onUploadBegin={() => {
          console.log("upload begin");
        }}
      />
      <input
        type="file"
        onChange={async (e) => {
          const file = e.target.files?.[0];
          if (!file) return;

          // Do something with files

          // Then start the upload
          await startUpload([file]);
        }}
      />
    </main>
  );
}
